baseURL = 'https://kap0503.github.io'
languageCode = 'en-us'
title = 'Annapoorna Prabhu'
theme = "archie"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle="PhD student @ Purdue University - AI/ML Security, Applied Cryptography"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kap0503"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Research"
url = "/posts"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience"
weight = 3

[[menu.main]]
name = "CV - soon..."
url = "/about"
weight = 4
